camera_name: 'camera'  #'camera unique name'
camera_namespace': 'camera' #'namespace for camera'
serial_no:  '' #'choose device by serial number'
usb_port_id:  '' #'choose device by usb port id'
device_type:  '' #'choose device by type'
# config_file:  '' #'yaml config file'
# json_file_path': '' #'allows advanced configuration'
initial_reset:  true #''
accelerate_gpu_with_glsl': "false" #'enable GPU acceleration with GLSL'
rosbag_filename:  '' #'A realsense bagfile to run from as a device'
log_level:  'info' #'debug log level [DEBUG|INFO|WARN|ERROR|FATAL]'
output': 'screen' #'pipe node output [screen|log]'
enable_color': true #'enable color stream'
rgb_camera.color_profile': '000' #'color stream profile'
rgb_camera.color_format:  'RGB8' #'color stream format'
rgb_camera.enable_auto_exposure': true #'enable/disable auto exposure for color image'
enable_depth': true #'enable depth stream'
enable_infra': true #'enable infra0 stream'
enable_infra1:  false #'enable infra1 stream'
enable_infra2:  false #'enable infra2 stream'
depth_module.depth_profile': '000' #'depth stream profile'
depth_module.depth_format:  'Z16' #'depth stream format'
depth_module.infra_profile': '000' #'infra streams (0/1/2) profile'
depth_module.infra_format:  'RGB8' #'infra0 stream format'
depth_module.infra1_format': 'Y8' #'infra1 stream format'
depth_module.infra2_format': 'Y8' #'infra2 stream format'
depth_module.exposure:  '8500' #'Depth module manual exposure value'
depth_module.gain:  '16' #'Depth module manual gain value'
depth_module.hdr_enabled': false #'Depth module hdr enablement flag. Used for hdr_merge filter'
depth_module.enable_auto_exposure': true #'enable/disable auto exposure for depth image'
depth_module.exposure.1:  '7500' #'Depth module first exposure value. Used for hdr_merge filter'
depth_module.gain.1:  '16' #'Depth module first gain value. Used for hdr_merge filter'
depth_module.exposure.2:  '1' #'Depth module second exposure value. Used for hdr_merge filter'
depth_module.gain.2:  '16' #'Depth module second gain value. Used for hdr_merge filter'
enable_sync:  false #"'enable sync mode'"
enable_rgbd:  false #"'enable rgbd topic'"
enable_gyro:  true #"'enable gyro stream'"
enable_accel': true #"'enable accel stream'"
gyro_fps': '20' #''
accel_fps:  '20' #''
unite_imu_method': "1" #'[0-None 1-copy 2-linear_interpolation]'
clip_distance:  '-2.' #''
angular_velocity_cov': '0.01' #''
linear_accel_cov': '0.01' #''
diagnostics_period': '0.0' #'Rate of publishing diagnostics. 0=Disabled'
publish_tf': false #'[bool] enable/disable publishing static & dynamic TF'
tf_publish_rate:  '0.0' #'[double] rate in Hz for publishing dynamic TF'
pointcloud.enable:  true #''
pointcloud.stream_filter': '2' #'texture stream for pointcloud'
pointcloud.stream_index_filter:  '0' #'texture stream index for pointcloud'
pointcloud.ordered_pc:  false #''
pointcloud.allow_no_texture_points': false #''
align_depth.enable': false #'enable align depth filter'
colorizer.enable': false #'enable colorizer filter'
decimation_filter.enable': false #'enable_decimation_filter'
spatial_filter.enable:  false #'enable_spatial_filter'
temporal_filter.enable': false #'enable_temporal_filter'
disparity_filter.enable:  false #'enable_disparity_filter'
hole_filling_filter.enable': false #'enable_hole_filling_filter'
hdr_merge.enable': false #'hdr_merge filter enablement flag'
wait_for_device_timeout:  '-1.' #'Timeout for waiting for device to connect (Seconds)'
reconnect_timeout:  '6.' #'Timeout(seconds) between consequtive reconnection attempts'}
global_time_enabled: false
